language: python

services: docker

python:
  - "3.6"

install:
  - pip install tox

script:
  - tox

deploy:

    # Deploy container to DockerHub
  - provider: script
    script: upload_plugins_images.sh
    on:
      branch: master
