language: python

services: docker

python:
  - "3.6"

install:
  - pip install tox

script:
  - tox

deploy:

  # release plugins images to DockerHub
  - provider: script
    script: release/plugins_images_dockerhub.sh
    on:
      branch: master

  # release image to DockerHub
  - provider: script
    script: release/image_dockerhub.sh
    on:
      branch: master
