version: "3.6"
services:

  postgres:
    image: postgres:10.1
    restart: always
    environment:
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
    volumes:
      - deeptracy-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U deeptracy" ]
      interval: 10s
      timeout: 5s
      retries: 5

  graphql-engine:
    environment:
      - POSTGRES_HOST

  deeptracy-buildbot:
    environment:
      - POSTGRES_HOST

volumes:
  deeptracy-data:
